import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import BottomNav from "@/components/layout/BottomNav";
import AuthSessionProvider from "@/components/auth/AuthSessionProvider";
import WishlistAuthBridge from "@/components/wishlist/WishlistAuthBridge";
import { getCurrentUser } from "@/lib/session/getSession";
import { VisitorProvider } from "@/components/providers/VisitorProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser()

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning >
        <AuthSessionProvider initialUser={currentUser}>
          <VisitorProvider />
          <WishlistAuthBridge />
          <Header />
          {/* pb-20 reserves space below content for the fixed BottomNav on mobile */}
          <div className="ui-container">
            {children}
          </div>
          <Footer />
          <BottomNav />
          <Toaster
            position="bottom-center"
            toastOptions={{
              style: {
                background: '#2A323F',
                color: '#E8E9EA',
                border: '1px solid rgba(255,255,255,0.1)',
              },
            }}
          />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
